apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shanari-argo-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/detianitatibs/shanari-shanari-infrastructure.git"
    path: kustomize/overlays/prod
    targetRevision: 6-build-gke
  destination:
    server: "https://kubernetes.default.svc"
    namespace: shanari-shanari
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
