apiVersion: apps/v1
kind: Deployment
metadata:
  name: shanari-shanari-fe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shanari-shanari-fe
  template:
    metadata:
      labels:
        app: shanari-shanari-fe
    spec:
      containers:
        - name: shanari-shanari-fe
          image: shanari-shanari-fe:v0.0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
